version: '3.8'

services:
  # Expo Mobile Development Server
  meditrack-mobile:
    build:
      context: .
      dockerfile: Dockerfile.mobile
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo CLI
      - "19002:19002" # Expo CLI
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - API_URL=http://meditrack-api:8000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - expo_cache:/home/expo/.expo
    depends_on:
      - meditrack-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: ["npx", "expo", "start", "--host", "lan", "--web"]

  # Backend API
  meditrack-api:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - QR_ENCRYPTION_KEY=${QR_ENCRYPTION_KEY}
      - ENVIRONMENT=development
    volumes:
      - backend_uploads:/app/uploads
      - backend_temp:/app/temp
      - ./BackEnd/db-twosides:/app/db-twosides
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: redis-server --appendonly yes

volumes:
  redis_data:
  backend_uploads:
  backend_temp:
  node_modules:
  expo_cache: